### ISSUE TITLE
README: "Error: SQLSTATE[HY000]: General error: 11 database disk image is malformed"

### ISSUE THREAD

**Issue by rfay** [phenaproxima/starshot-prototype#137]
There's a whole section on changing Docker Desktop *not* to use VirtioFS.

But I've never, ever seen the message `SQLSTATE[HY000]: General error: 11 database disk image is malformed`, nor should that happen with any Docker provider.

And since DDEV is, by default on macOS, using mutagen, the mounts don't even work that way. 

You shouldn't have to do any of this with DDEV for Starshot or anything else. 

I'll be happy to PR the removal of this section, or I'll be happy to help debug this if anybody can demonstrate it. Mostly VirtioFS is the only mounting technology Docker Desktop on the mac is really supporting. I don't recommend gRPC FUSE or osxfs (Legacy). The reality is I don't recommend Docker Desktop, but that's because of poor support, not because of this. 

I don't find any issues with this error in the Docker Desktop issue queue, https://github.com/docker/for-mac/issues?q=+%22database+disk+image+is+malformed%22+

**Comment by rfay** [comment]
Poking around the internet, this seems to be a sqlite3 disk failure. Since starshot now uses mariadb:10.11 as its default database, it shouldn't be an issue anyway. 

I'm not sure where starshot was previously putting the sqlite file, but I'd be interested to know! If it was in a bind-mounted directory, maybe something interesting could happen. (It would be best on a docker volume, not bind-mounted, since it doesn't need to be bind-mounted anyway.)

**Comment by phenaproxima** [comment]
> Since starshot now uses mariadb:10.11 as its default database, it shouldn't be an issue anyway.

That's a fair point. I'm okay removing it.

**Comment by phenaproxima** [comment]
Merged #138.
