### ISSUE TITLE
Installing starshot using recipes no longer works

### ISSUE THREAD

**Issue by thegbomb** [phenaproxima/starshot-prototype#141]
I tried to run drush si ../recipes/starshot and it failed with dependency errors.

**Comment by thegbomb** [comment]
https://github.com/phenaproxima/starshot-prototype/pull/140

**Comment by phenaproxima** [comment]
> drush si ../recipes 

This...this is not a thing. You'd need to specify which recipe to install from, I'd think.

**Comment by phenaproxima** [comment]
Also, here's the thing that gets me about this issue...I put installation instructions in the README.

They work, and are _tested_, automatically and continuously, by [the CI process we put in place](https://github.com/phenaproxima/starshot-prototype/actions). It doesn't seem fair to me to expect it to work if you deviate from the documented, tested instructions.

For this reason, I think I'm closing this as a wontfix.

**Comment by thegbomb** [comment]
Sorry, you are right, the PR and issue was made in haste. Apologies.

I am starting to look into providing new recipes for Starshot. e.g an accessibility recipe. But in order for me to get them to install I was deviating from the documented installer route to be able to test the recipe I created. I am using 'drush si --yes ../recipes/starshot'.

I need to look into how to install a recipe into an existing site, but also need to reset the config, and re install (after I have found and fixed issues). I found it easilest to just do the recipe install from an empty site install point.

I know there was some work done to get Drush to support site:install using a recipe and am sure this worked in here at some point, but obviously it is not (yet) a supported installation process.

I raised the PR as it didn't look like it was going to affect the current installation process, but the new advances haven't been also added to the recipes part of the project to keep that in sync. e.g. the notify_new_comments isn't working in the current recipe and there are still references to the project_browser which looks to have been removed but not fully among other things (fixed in the PR).

I thought this might be helpful to others looking to support the project with new recipes.

**Comment by phenaproxima** [comment]
HELL yeah - you make a bunch of excellent points. I knew something useful could come out of this!

And you are absolutely right - if you want to add a new recipe to the prototype, there's no explanation for that at all. (It's actually quite a bit simpler than you think 😉) But it's not documented at all, and I think it makes perfect sense for me to write a `CONTRIBUTING.md`, or a wiki page, that explains how to add a new recipe to this prototype. Then you can test it out by adding the beginnings of an accessibility recipe in a PR. (Thanks for working on that, by the way!)

How does that sound?

**Comment by phenaproxima** [comment]
In my excitement, I took a shot at this: https://github.com/phenaproxima/starshot-prototype/wiki/Contributing.

Is that helpful? I think I'd be okay putting that in a `recipes/example` directory, along with a template `composer.json` and a script for modifying the parent `composer.json`, just to help contributors along. What an awesome idea.

**Comment by thegbomb** [comment]
Amazing, thank you. I had just copied one of the existing recipes and amended, but the documented way is much better.

I have also updated the PR to include a more thorough description, as I believe there is still a couple of bugs in the current starshot recipe.

**Comment by phenaproxima** [comment]
I don't think those are bugs in the current recipes; it's that you can't do a direct installation from the recipes right now due to missing upstream functionality in core. It's best to rely on the `drupal:install` script in the top-level `composer.json`, since it accounts for these quirks. The goal is definitely to allow `drush si recipes/starshot`, but we're not quite there yet. You can be sure that the `drupal:install` script will, in fact, do things that way as soon as it's possible.
