### ISSUE TITLE
Should Drupal CMS automatically install itself?

### ISSUE THREAD

**Issue by phenaproxima** [phenaproxima/starshot-prototype#4]
Right now, Drupal CMS automatically spins itself up into a SQLite database when you do `composer create-project`. Is that overzealous? Should it perhaps be a second command (a simple script in `composer.json`)? So you'd do something like:

```
composer create-project phenaproxima/drupal-suite mysite
cd mysite && composer install-drupal
```

The balance we're trying to achieve here is being as easy and painless as possible to get up and running (thus the choice of SQLite), without becoming overbearing.

**Comment by thejimbirch** [comment]
Does it work on Windows the same as it does on Mac/Linux?

I have been super impressed with the speed on the drupal quick-start script.  If this is cross platform and negates the need for the Docker based tools, I think that would be a win.

**Comment by phenaproxima** [comment]
Well...it _should_. But I'm not sure.

Windows is tricky 'cause it's just gotta do weird shit all the time. That said, I bet this would work reasonably well on WSL. But Windows users might want to favor Docker-based things for a lot of other reasons.

That said, the self-installation thing is using the script that is part of core, so it should be as compatible with Windows as core itself is willing to be.

**Comment by phenaproxima** [comment]
I'm leaning towards removing the "immediately install upon project creation" thing. I think it's okay to add _one_ more step.

What I propose is that you'd do this, _regardless_ of your preferred dev environment:

```
composer create-project yadda-yadda...
cd project-dir
```

Then you could either do this if you're _not_ using DDEV:
```
composer drupal:quick-start
```
This would install into a SQLite database and open it.

Or, if you _are_ wanting to use DDEV:
```
ddev quick-start
```

IMHO this would be a completely reasonable set of installation steps. Two commands (three if you include the `cd`), one of which would be copy-pasteable.

**Comment by phenaproxima** [comment]
The previous comment is now implemented and documented. The installation is no longer a one-liner; it's a grand total of...2 commands. Three if you count the 'cd' into the project directory. Still extremely easy, and on par with other modern software.

The choice has been made, so I'm closing this issue.
