### ISSUE TITLE
As a site builder I want to install additional functionality through the UI after initial site installation. E.g Multilingual.

### ISSUE THREAD

**Issue by balsama** [phenaproxima/starshot-prototype#48]
Recipes provided by Drupal CMS should be grouped into two main categories:

1. Installed by default
2. Not installed by default

Recipes in Category 2 should be exposed in the UI via project browser. To start, the `starshot_multilingual` recipe should fall into Category 2.

Remaining tasks:

- [x] #37 
- [ ] #74
- [ ] Expose local filesystem Recipes marked with `featured=true`
- [ ] Redirect to Project Browser at the end of installation

**Comment by phenaproxima** [comment]
> Redirect to Project Browser at the end of installation

I'm not sure this is actually gonna happen. The way things work now, with the CLI-based instant installation, you open a one-time login link (via `drupal install`) and I don't know if the redirection destination for that is customizable.

So I would probably say we should remove that from the task list.

**Comment by balsama** [comment]
"Redirect to Project Browser" is probably overly simplistic. In reality, we want to the default experience to expose those options somehow, but we should think about why and how. Redirecting there when we open the browser from the command line actually probably isn't actually desirable since the purpose of that is to put them into the front-end of the application. Not a configuration screen.

Maybe a shortcut to the Project Browser with a descriptive title would be best?

When we allow a site to be installed from a recipe _through the UI_, then I think exposing the Project Browser as an install step would be prudent.

**Comment by phenaproxima** [comment]
#74 will address this request - it removes multilingual support from the main `starshot` recipe, instead exposing it to Project Browser.

**Comment by phenaproxima** [comment]
This is completely done as of ce585df58808178d3dd01c026a3f2d3a3aa251e2.
