### ISSUE TITLE
Add DDEV support

### ISSUE THREAD

**Issue by gitressa** [phenaproxima/starshot-prototype#49]
It would be nice if quick-start does not run, if the environment is DDEV. For now, the workaround is this method, to be included in the README:

> ### DDEV installation
> If you don't have PHP and Composer installed on your host machine, you can try in [DDEV](https://ddev.readthedocs.io):
> ```
> mkdir starshot && cd starshot
> ddev config --project-type=drupal --docroot=web
> ddev start
> ddev composer create drupal/starshot-project --repository='{"type":"vcs","url":"https://github.com/phenaproxima/starshot-prototype"}' --stability=dev
> ```
> After the download completes, you probably get an error since `drupal quick-start` doesn't work in DDEV. Stop the server with Ctrl-C, and create login link:
> ```
> ddev drush uli -l https://starshot.ddev.site
> ```

Maybe one or more custom commands can be created, to make the DDEV installation work smoother?

**Comment by gitressa** [comment]
I created https://github.com/ddev/ddev/issues/6158 to alert DDEV developers about this issue.

**Comment by phenaproxima** [comment]
#50 fixes this.
