### ISSUE TITLE
As a contributor to Drupal CMS, I want development to take place in a single repo.

### ISSUE THREAD

**Issue by balsama** [phenaproxima/starshot-prototype#70]

**Comment by phenaproxima** [comment]
Do we really need this issue to be open? It's a non-issue in _this_ repo, and ultimately it's going to be a technical and governance decision in the final home for Starshot (which will be drupal.org's GitLab instance). I've already been strongly advocating for a monorepo architecture, and have heard no real resistance to the idea, but we're blocked on having a final Starshot product name. (Which is the _dumbest_ thing to be blocked on, in my opinion, but it's out of my hands.)

**Comment by phenaproxima** [comment]
Closing for now, feel free to reopen if there's anything else we need to discuss.
