### ISSUE TITLE
As a distribution builder or site builder, I want the recipes included in Drupal CMS to be available as standalone packages so that I can reuse them in my distribution or site without using Drupal CMS's scaffold project.

### ISSUE THREAD

**Issue by balsama** [phenaproxima/starshot-prototype#71]
#70 implies that all of the recipes will be developed in a monolith repo (as it is currently). But we should have automation that splits the atomic Recipes into their own repos for distribution so that they can be reused outside of the scaffold project for both distribution builders and individual site builders.

**Comment by phenaproxima** [comment]
Yup, agreed on this. I'm not sure how to set up the subtree split, but at least there's prior art on that. This is most definitely blocked until Starshot finds its permanent home under DA control (most likely on GitLab...at least, that's what I hope for).

**Comment by phenaproxima** [comment]
Just for visibility - this is something I discussed with Alex Pott. The plan is for all recipes (yes, _all_ recipes) to be their own tiny Composer packages. Starshot would then become two things:

1. A metapackage that brings in all the component recipes, the same way `drupal/core-recommended` works.
2. A template project that sets up Starshot with quick installs, DDEV integration, etc.

**Comment by simesy** [comment]
Why wouldn't (in time) all the recipes used by starshot just be avaialble in the project browser?

**Comment by phenaproxima** [comment]
@simesy: I think that is, eventually, the exact aim. But there's a lot of infrastructure that needs to happen for that first, across several initiatives and at the DA's end.

**Comment by simesy** [comment]
Yes agreed, i see how it's a good thing at this point.

**Comment by phenaproxima** [comment]
This was sorta-kinda done in #109. Obviously the recipes aren't coming from Packagist, but now this is an example of how one could create a recipe as a small package and compose recipes together.

**Comment by phenaproxima** [comment]
I think that I can close this out; the only way in which this isn't, like, done is the fact that we're not actually publishing these things to Packagist. But that's okay -- this is the prototype, not the final product. In the final product, we _are_ going to publish recipes as their own things, and here in the prototype you can see the model of how we'll do it.

So I'm closing this bad boy.
