### ISSUE TITLE
Integrate Tugboat for automated demo environments

### ISSUE THREAD

**Issue by TravisCarden** [phenaproxima/starshot-prototype#8]
Set up [Tugboat](https://www.tugboatqa.com/) integration to automatically deploy live test-and-demo environments for DrupalCon.

- [x] https://github.com/phenaproxima/starshot-prototype/pull/25
- [x] Rebuild the main preview every ~12 hours~ _day_ (24 hours is the smallest frequency)
- [x] Generate previews for PRs
- [x] Refresh PR previews with new commits

It looks like Tugboat only generates previews automatically for PRs sent from the canonical repo, not from forks. That probably makes sense, since anyone could send a PR that does something malicious. But we can still initiate previews for them manually. So I'm calling this done.

**Comment by TravisCarden** [comment]
@phenaproxima do you have any specific requirements to add? Or should I just use my judgment until I have questions.

I do have one thing off the bat: since the repo is on your account, I think you need to [authorize Tugboat](https://docs.tugboatqa.com/setting-up-tugboat/connect-with-your-provider/#how-do-i-link-tugboat-to-github)--and possibly create the Tugboat project (I haven't researched that far yet). I'll continue researching and reading documentation, but I believe I'm blocked on actually doing the work until you do that part for me.

**Comment by TravisCarden** [comment]
Great, @phenaproxima. Can you [add me to the crew](https://docs.tugboatqa.com/administer-tugboat-crew/add-a-user/)?

**Comment by phenaproxima** [comment]
Invite sent.
