### ISSUE TITLE
Recipe info displays instead of module info in project browser

### ISSUE THREAD

**Issue by pameeela** [phenaproxima/starshot-prototype#80]
With the update to expose recipes in the UI, when you click on a module in PB, you just see the page for the one recipe.

![Kapture 2024-05-17 at 16 32 40](https://github.com/phenaproxima/starshot-prototype/assets/961993/0fa91367-ab29-4093-857f-a98e97e8bf8e)

**Comment by phenaproxima** [comment]
I'm pretty sure that's a preexisting condition in Project Browser, but I'll confirm.

This is the problem with using the mocked drupal.org source - it's meant for testing and demoing _only_, not actual use. We could do a quick hotfix to just disable that source, but that would mean Project Browser in Starshot would go back to looking kinda sad, with only one lonely recipe in it.

**Comment by pameeela** [comment]
Do you mean that the project pages don't work in default PB? That's definitely not the case currently, you can view the project info per page.
![Kapture 2024-05-20 at 10 55 55](https://github.com/phenaproxima/starshot-prototype/assets/961993/605a0a63-506a-4846-a68b-aeb334e66a76)

**Comment by phenaproxima** [comment]
@pameeela Project Browser has a lot of problems where it has many hard-coded assumptions that everything is a module and needs to work similarly. I've been working on untangling all that but it's a bit of a haul. With the change to Project Browser 2.0.0-alpha1, maybe this is improved now? Would you be willing to test again?

**Comment by pameeela** [comment]
@phenaproxima on a fresh install, the browse page is only showing recipes, I can't access PB proper.

![Uploading Screenshot 2024-06-24 at 9.46.23 am.png…]()

**Comment by phenaproxima** [comment]
That's correct - currently, we disable the module list since they're all based on mock data. Easy enough to restore, though.

**Comment by pameeela** [comment]
Oh, I see, well I can't test it then!

**Comment by phenaproxima** [comment]
D'oh! Here, run this Drush command to restore it:

```
drush cset -y project_browser.admin_settings enabled_sources "[drupalorg_mockapi, recipes]" --input-format=yaml --yes
drush cr
```

That should restore it.

**Comment by pameeela** [comment]
The module pages are just blank now:
![Screenshot 2024-06-24 at 10 07 50 am](https://github.com/phenaproxima/starshot-prototype/assets/961993/a8bc9792-fea8-48ae-bf8a-49e3aba500f9)

**Comment by phenaproxima** [comment]
Yeah, this is an upstream issue we've been seeing. I don't think Starshot introduced it, nor did recipe support in Project Browser (or the tests would have caught it).

**Comment by pameeela** [comment]
Ah ok, well happy to close this issue as it seems like it's a moving target anyway.
