### ISSUE TITLE
Use Geofield and Leaflet modules for maps, to respect user privacy

### ISSUE THREAD

**Issue by gitressa** [phenaproxima/starshot-prototype#81]
To respect user privacy, usage of external resources should be kept at a minimum, or avoided entirely.

The Geolocation module contacts the external web site unpkg.com for the https://unpkg.com/leaflet@1.8.0/dist/leaflet.js file, when it shows the map on _/event/2024/nasas-boeing-crew-flight-test-launch_. The maintainer stated in [Allow to choose between local or external libraries](https://www.drupal.org/project/geolocation/issues/3023494) that:

> I think it's pretty likely that some people want to host the libraries locally, but they can do so using hook_js_alter() as they deem fit. Providing all the plumbing to handle this in a form and keeping this up to date in the future seems to much effort for an each case that can be solved fairly easily anyway.

So we could instead use [Geofield](https://www.drupal.org/project/geofield) module with the [Leaflet](https://www.drupal.org/project/leaflet/) module.

~~Leaflet module _does_ currently contact fastly.net, but as soon as [Support serving local scripts first, use CDN as fallback](https://www.drupal.org/project/leaflet/issues/3447832) is fixed, Geofield with Leaflet ought to only contact the relevant map resource, which is openstreetmap.org~~. I was mistaken, [OpenStreetMap uses fastly.net to serve its tiles](https://www.fastly.com/blog/how-openstreetmap-uses-our-modern-cdn-to-push-near-instant-updates-worldwide/), so fastly.net is necessary, and all is well with the Leaflet module.

## Remaining tasks

Switch from Geolocation to Geofield and Leaflet.

**Comment by phenaproxima** [comment]
I'm totally open to this idea; the goal at the time I used Geolocation was to just get a freakin' map working on the event page in time for DrupalCon 😅 I tried with Geofield but I could NOT, for the life of me, figure out how to configure it. So in other words, I ran into the exact kind of problem that Starshot aims to solve.

If you (or someone else?) submits a PR which changes to Geofield and Leaflet, whilst keeping the zero-setup, oh-look-I-immediately-have-a-working-map experience of the Event content type, then I will gladly merge that.

**Comment by gitressa** [comment]
Sounds fantastic, thanks for being open for this update! And yes, getting all the pieces to fit together for Geocoder, Geofield, et al can be challenging :)

I recently documented [how to set up Geocoder to work with GPX-files](https://www.drupal.org/docs/extending-drupal/contributed-modules/contributed-module-documentation/geofield/using-gpx-files-with-geocoder-and-geofield) based on a fantastic step-by-step guide by @FMB in [Document GPX File Parsing Provider](https://www.drupal.org/project/geocoder/issues/2747193#comment-11829776).

I would love to try to update the Starshot recipe, but I haven't worked with Recipes yet ... so I would probably have to spend some time understanding how it fits together. So instead of trying to create the new set up in a recipe, I decided to instead document how to set up Geocoder, Geofield and Address module in [Using Address module with Geocoder and Geofield](https://www.drupal.org/docs/extending-drupal/contributed-modules/contributed-module-documentation/geofield/using-address-module-with-geocoder-and-geofield), perhaps you could give it a try?

After going through the steps in the documentation, to show the map in Starshot, you can add a "Map" block in Layout Builder. Click "Manage Layout" and then:

- Click "Configure Section 3"
- Add "Map", with these settings: 
  - Formatter: Leaflet
  - Zoom: 16

Please let me know if any of the steps does not make sense, so I can update the documentation, thanks!

**Comment by gitressa** [comment]
OpenStreetMap, and the sites it contacts are located in these countries outside EU, which conflicts with GDPR compliance:
- openstreetmap.org: Canada/United States
- fastly.net: Canada/United States
- unpkg.com: Canada/United States

https://maps.wikimedia.org could be considered as an alternative map tile source, since it is located in the Netherlands when I checked with https://check-host.net/ip-info?host=maps.wikimedia.org.

We can use the https://git.drupalcode.org/project/leaflet_more_maps/ module to support this map provider.

**Comment by gitressa** [comment]
I found an alternative tile provider https://openstreetmap.de/, which only contacts a single domain for map tiles, which is openstreetmap.de hosted at Hetzner in Germany.

I created the issue [Add support for GDPR-friendly openstreetmap.de](https://www.drupal.org/project/leaflet_more_maps/issues/3449579). Feel free to review, so that we perhaps can use that as map service for tiles in Starshot?

**Comment by gitressa** [comment]
Good news, everyone! Leaflet More Maps 2.2.0 was just released, and it includes many improvements (see [[Meta] Release version 2.2](https://www.drupal.org/project/leaflet_more_maps/issues/3410669)) among them the option of using openstreetmap.de for Leaflet tiles, completed via [Add support for GDPR-friendly openstreetmap.de](https://www.drupal.org/project/leaflet_more_maps/issues/3449579).

**Comment by gitressa** [comment]
I am still not sure how to work with recipes ... is there a documentation page which describes the basics?

If not, here are the steps for adding this feature, it shouldn't take an experienced Drupal developer too long:

## Using Address module with Geocoder and Geofield

<p>Here's how to set up <a href="https://www.drupal.org/project/geofield" rel="nofollow">Geofield</a> and <a href="https://www.drupal.org/project/geocoder" rel="nofollow">Geocoder</a> to look up an address supplied via the <a href="http://www.drupal.org/project/address" rel="nofollow">Address</a> module, and show it with <a href="https://www.drupal.org/project/leaflet" rel="nofollow">Leaflet</a> (optional).</p>
<ol>
<li>Install Address, Geocoder, Geocoder Address, Geocoder Field, Geocoder Geofield,&nbsp;Geofield, and Leaflet (optional)</li>
<li>Install a provider, for example Nominatim (used by OpenStreetMap):<br>
  <code class=" language-php">composer <span class="token keyword keyword-require">require</span> geocoder<span class="token operator">-</span>php<span class="token operator">/</span>nominatim<span class="token operator">-</span>provider</code></li>
<li>Create a "Nominatim" Geocoder provider under <em>/admin/config/system/geocoder/geocoder-provider:</em>
<ul>
<li><strong>Root URL</strong>: <a href="https://nominatim.openstreetmap.org" rel="nofollow">https://nominatim.openstreetmap.org</a></li>
<li><strong>User Agent</strong>: Value of the User-Agent header, for example "Drupal example.org". Replace "example.org" with your URL.</li>
<li><strong>Referer:</strong> Value of the Referer header, for example "<a href="https://example.org" rel="nofollow">https://example.org</a>". Replace with your URL.</li>
</ul>
</li>
<li>Create an Address field called "Location" in a content type, to supply an address</li>
<li>Create a Geofield field called "Map" in a content type, allowing only one value</li>
<li>Set up the Geofield field like this:
<ul>
<li>Geocode → Geocode from an existing field</li>
<li>Geocode from an existing field → select "Location [Address]"</li>
<li>Geocoder providers → check "Nominatim"</li>
</ul>
</li>
<li>For the Geofield field, in "Manage display" choose "Leaflet Map" (if available) or just "Raw Output"</li>
</ol>
<p>To test if it works, create new content, filling out the Address field. After saving the node, the coordinates for the address should be looked up, and the Leaflet map should show the location on the map.</p>

https://www.drupal.org/docs/extending-drupal/contributed-modules/contributed-module-documentation/geofield/using-address-module-with-geocoder-and-geofield

**Comment by phenaproxima** [comment]
That all seems doable enough. Assigning to myself to get it done.

**Comment by phenaproxima** [comment]
> User Agent: Value of the User-Agent header, for example "Drupal example.org". Replace "example.org" with your URL.
> Referer: Value of the Referer header, for example "https://example.org/". Replace with your URL.

These are problematic for us because, at install time, we don't _know_ what our URL is or will be.

Can these be anything that _look_ like a URL? For example, could I set a value of `http://drupal-SOME_UUID.localhost`?

**Comment by gitressa** [comment]
I think that would be all right, and for show casing work fine. But the user probably needs to update those values before going live.

**Comment by gitressa** [comment]
Two tips: I just  went through the process, and enabled the modules with Drush:

```
drush in address geocoder geofield leaflet leaflet_more_maps geocoder_address geocoder_geofield geocoder_field
```

Also, when setting the display to use "Leaflet Map" (Step 7) under settings, set "Leaflet Map Tiles Layer" to "OpenstreetMap.de".

**Comment by mlncn** [comment]
Would it make sense to use tokens in the site-URL-dependent geocoder provider settings?  If it does make sense and would solve our problem but it is not yet possible, we could open an issue to add token support?

**Comment by gitressa** [comment]
Adding token support is a great idea @mlncn.

**Comment by gitressa** [comment]
I guess it needs to be added in the individual Geocoder Plugins, like this one? https://git.drupalcode.org/project/geocoder/-/blob/8.x-4.x/src/Plugin/Geocoder/Provider/Nominatim.php.

**Comment by gitressa** [comment]
Thanks for creating the PR @phenaproxima, it works well. I just have a single comment, about using openstreetmap.de instead of openstreetmap.org, via [Leaflet More Maps](https://www.drupal.org/project/leaflet_more_maps).

**Comment by gitressa** [comment]
Thanks for being open to this @phenaproxima, and for solving all the the difficult tasks to allow it to happen, I very much appreciate it.
