### ISSUE TITLE
Consider disabling user registration by default

### ISSUE THREAD

**Issue by pameeela** [phenaproxima/starshot-prototype#88]
Got to thinking when testing #86, should we modify the default user settings in Starshot to disable user registration? Certainly in my experience, it is rarely needed, and far more often I find sites where it isn't needed but no one knew to turn it off so they get filled with spam accounts.

Wondering what others thing? I'm not saying that user registration isn't needed, just that I think it's better as opt-in than opt-out.

**Comment by gitressa** [comment]
I agree @pameeela, the sane default would be to set **Who can register accounts?** to **Administrators only** under **Registration and cancellation**, to prevent spam accounts.

https://www.drupal.org/docs/user_guide/en/config-user.html#s-steps

**Comment by pameeela** [comment]
Thanks @gitressa yes that's exactly what I meant, thank you for providing the precise details where I was a bit vague!

**Comment by gitressa** [comment]
You're welcome, and thanks for all your work on Starshot, I really appreciate it! Starshot will be a game changer, and help make the world realize the power of Drupal, which is currently kind of hidden.

**Comment by phenaproxima** [comment]
+1 for this, actually. I never really thought about it, but you're right -- in most(?) configurations, disabling user registration by default makes sense.

If someone files a PR for this, I will gladly merge it.

**Comment by pameeela** [comment]
Created #90
