### ISSUE TITLE
Consider adding "All in One Accessibility" module

### ISSUE THREAD

**Issue by skynetindia** [phenaproxima/starshot-prototype#89]
Websites should be accessible to individuals with disabilities, ensuring equal access to information and services. Ethically, accessible websites promote inclusivity, allowing all users, regardless of their abilities, to engage fully with digital content.

The module https://www.drupal.org/project/all_in_one_accessibility provides many features that improve Drupal website ADA compliance and browser experience.

**Comment by phenaproxima** [comment]
In fact, on closer review, the only real code in this module is just...licensing-related.

I think I'm calling it -- this isn't acceptable for Starshot. Sorry.
