### ISSUE TITLE
Consider adding 'focal_point’ module

### ISSUE THREAD

**Issue by isalmanhaider** [phenaproxima/starshot-prototype#93]
### Motivation:
I talked about Drupal Starshot to my sister, and she installed it and started exploring. While creating pages, she asked for this feature, as she recently launched a blog on WordPress where this feature is available out of the box. In WordPress, when you upload an image, you can choose the focal point.

Adding the Focal Point module will help both beginner and professional developers exploring Drupal Starshot, making it easier to compare with platforms like WordPress, HubSpot, or similar services where they can launch websites or landing pages. This module will enhance user experience by providing better control over image presentation, aligning Drupal Starshot with user expectations from other popular platforms.

https://www.drupal.org/project/focal_point

**Comment by phenaproxima** [comment]
Focal Point has been in Starshot since 95403088. :)
